### ISSUE TITLE
ClockFaceFatHands-glyphs svgs have inconsistent names

### ISSUE THREAD

**Issue by wyuenho** [ocodo/ClockFace-font#4]
This makes batch processing SVG files names slightly more annoying 

https://github.com/ocodo/ClockFace-font/commit/632f7181d814da58c5fa80b2cb9540000760019b#commitcomment-111386539

**Comment by jasonm23** [comment]
Please edit the issue description to explain what you want instead.  Or the issue will be closed.

Note that other than the font output all files are temporary/auto generated, and are only included in the project to illustrate the creation steps.

**Comment by wyuenho** [comment]
Instead of `clock_00_45_.svg`, I'd like `clock_00_45.svg`. You need to fix your auto generation script to remove the extra underscore. The SVG source files are useful as icons by themselves.

**Comment by jasonm23** [comment]
I need to?

Sorry what?

**Comment by jasonm23** [comment]
Open source software maintainers are volunteers who donate their time and expertise to create and maintain software that is freely available to the public. They do this out of a desire to contribute to the community and to make a positive impact on the world.

While users of open source software are certainly entitled to voice their opinions and concerns, it's important to remember that maintainers are not obligated to implement every suggestion or fulfill every request. They have limited time and resources, and they must prioritize their efforts based on their own goals and the needs of the community.

In terms of etiquette, the Free Software Foundation (FSF) has a set of guidelines known as the Four Freedoms (FFF) that are commonly used to define the ethical principles of open source software. These are:

1. The freedom to run the program as you wish, for any purpose.
2. The freedom to study how the program works, and change it to make it do what you wish.
3. The freedom to redistribute copies so you can help others.
4. The freedom to distribute copies of your modified versions to others.

These freedoms are intended to promote collaboration, innovation, and the common good. As a user of open source software, it's important to respect these freedoms and to treat maintainers with courtesy and gratitude for their contributions to the community.

So, while you are certainly entitled to express your opinions and feedback on open source software, it's important to do so respectfully and with an understanding of the limitations and priorities of the maintainers. It's also important to be aware of and abide by the ethical principles of the FFF. By doing so, you can help to create a more collaborative and positive community around open source software.

**Comment by wyuenho** [comment]
I'm going to remove support for clockface just so I don't have to interact with emacs user as much.

**Comment by jasonm23** [comment]
Your presence will be missed terribly.
